name: Create release, build and upload artifacts

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build-and-upload:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: debian-bookworm
            target: x86_64-debian-bookworn-linux-gnu
          - os: debian-trixie
            target: x86_64-debian-trixie-linux-gnu
            
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        if: startsWith(matrix.os, 'debian')
        run: |
          sudo apt-get install -y pkg-config libasound2-dev protobuf-compiler

      - name: Build and upload binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: qobuz-player
          target: ${{ matrix.target }}
          zip: all
          token: ${{ secrets.GITHUB_TOKEN }}
